// Generated by https://quicktype.io

export interface VentasResponse {
	_id:         string;
	codCliente:  number;
	provCliente: string;
	codVendedor: string;
	nomCliente:  string;
	importe:     number;
	regFecha:    string;
}


