// Generated by https://quicktype.io

export interface LocationsResponse {
	_id:         string;
	title:       string;
	lngLat:      number[];
	provincia:   string;
	description: string;
	agente:      string;
	__v:         number;
}
