// Generated by https://quicktype.io

export interface LocationsResponse {
	_id?:         string;
	title:       string;
	lngLat:      number[];
	provincia:   string;
	description: string;
	agente:      string;
	telefono: number;
	email: string
	__v?:         number;
}
